### PR TITLE
Pipeline updates

### PR DESCRIPTION
**Pull request by patmarion**

### CODE REVIEW

**Comment by manuelli** [comment]
LGTM.

Do you have your data folder structured correctly for these changes? I guess the main one is just moving object_data.yaml into the data directory. If so can we update the documentation to remove the UnderConstruction label [here](https://github.com/RobotLocomotion/LabelFusion/blob/pipeline-updates/docs/pipeline.rst#under-construction)?

**Comment by patmarion** [comment]
Correct, for this to work the data folder needs `object_data.yaml`.  I uploaded the latest and greatest version of this file into our slack channel.  I put the file in my local copy of the data.

**Comment by patmarion** [comment]
I'm not ready to remove the under construction warning for that doc file.  I just updated some paths, but i didn't really go over the whole file.

**Comment by manuelli** [comment]
Ok fair enough on the documentation. I'll update it as I go along running the pipeline.

**Pull request merged**
