### PR TITLE
Save depth images

### PR DESCRIPTION
**Pull request by 5yler**
Modified `imagecapture.py`  module to support saving 16 bit depth in addition to RGB images. Works but the output images are 16 bit 3 channel, ideally they would be single channel.

### CODE REVIEW

**Comment by peteflorence** [comment]
Thanks @5yler !  This looks good to me, I just will test it back in lab before merging.

**Comment by 5yler** [comment]
@peteflorence Any idea on how to make the `vtkPNGWriter` save a single channel image?

**Comment by patmarion** [comment]
If the vtkImageData has only 1 component but the vtkPNGWriter saves the image with 3 components then it's possible that the writer does not have support for single channel images.  I'll try to take a look at the API and see if there's a way to make it work.

In the meantime, an easy workaround is to re-open the image and re-save it with 1 channel.  The first part of this script shows how to use the `imread` function of scipy to read the image and then extract the first channel.  Then you could use `imsave` to overwrite it.

https://github.com/RobotLocomotion/LabelFusion/blob/master/scripts/plotLabels.py
https://github.com/RobotLocomotion/LabelFusion/blob/master/scripts/plotLabels.py#L25

**Comment by peteflorence** [comment]
Yes I was thinking of going the route @patmarion suggested as the workaround -- change it to 1-channel after it's in 3-channel.

Testing this now!

**Comment by peteflorence** [comment]
So @5yler @patmarion seems like everything is good actually with the amount of channels -- I am finding that the saved depth.png are actually single channel.

If I save the image with the vtkPNGWriter, and then open it, I get this print out:

```
writing: /root/labelfusion/data/logs_test/moving-camera/images/0000000001_depth.png
width x height: 640 x 480
shape: (480, 640)
ndim: 2
num channels: 1
```
From:

```
        print 'writing:', imageFilename
        ImageCapture.writeImage(image, imageFilename)

        img = scipy.misc.imread(imageFilename)

        print 'width x height: %d x %d' % (img.shape[1], img.shape[0])
        print 'shape:', img.shape
        print 'ndim:', img.ndim

        
        # extract one channel
        if img.ndim in  (3, 4):
            print 'num channels:', img.shape[2]
            img = img[:,:,0]
        else:
            assert img.ndim == 2
        print 'num channels: 1'
```

**Comment by peteflorence** [comment]
Checking out a couple more things, and then close to PR

**Comment by peteflorence** [comment]
So question for all @patmarion @5yler @manuelli --

The depth images are not 100% synced with the rgb images, as expected -- if I print out the `utime` for each, I get for example:

`1491422444817783` for `0000000001_depth_utime.txt`
`1491422444813686` for `0000000001_rgb_utime.txt`

This PR currently only saves the rgb utimes, which are the only ones used for masking.  

Should we:
1. Not worry about it and leave PR as is, and not save depth utimes, since they're not used for anything,
2. Save the depth utimes but don't do anything with them, or
3. Save the depth utimes and also make masks for the depths

My vote is #1

**Comment by patmarion** [comment]
I'd say 1 or 2.  I'd also like to eventually change the pipeline so that all utimes are saved in a single file rather than writing a `.txt` file for each.

I think this PR should be modified so that saving depth is a command line option, and it should be modified so that it only does one pass over the log.  Currently it does two passes and calls `readFromLog` twice.

I just checked and the `LcmLogReader` in `ElasticFusion` uses the timestamp from the `images_t` message, and the openni2 lcm driver sets the `images_t` utime field to be the utime of the depth image, so I think that part is probably correct.

**Comment by patmarion** [comment]
btw, this PR seems to be adding .pyc files accidentally

**Comment by patmarion** [comment]
Oops, I guess when I extracted `LabelFusion` I forgot to update the `.gitignore` file with the regexs in spartan.  It should have some of these:

https://github.com/RobotLocomotion/spartan/blob/master/.gitignore

**Comment by peteflorence** [comment]
OK that was my bad bringing in the .pyc files (I must have `git add -A` without `.gitignore` protection)

I'll close this PR, branch off @5yler's branch before the .pyc files and:

- Re-add that last commit without .pyc
- Default to not saving depth images and add command line arg to save them
- Add pyc etc to `.gitignore`

If people would like to later, can:

- change `imagecapture.py` to only do one pass through the data (it's plenty fast as it right now though)
- separately save depth utimes, or overhaul how the pose data is saved

**Comment by peteflorence** [comment]
Thank you @5yler for implementing this!

Sorry to mess up your PR and then close it, but I'm merging the fixed version here https://github.com/RobotLocomotion/LabelFusion/pull/11  (you should show up as a project contributor now :+1:)

**Pull request closed without merging**
